before_script:
  # Print out python version for debugging
  - python -V

test:
  script:
    - python -m venv .\venv
    - venv\Scripts\python -m pip install -r requirements.txt
    - venv\Scripts\python -m pytest
